import React, { useState, useRef, useEffect } from 'react';
import { Download, FileText, Code, ChevronDown } from 'lucide-react';

const exportAsMarkdown = (video) => {
  const { title, channelName, url, analysis } = video;
  const lines = [
    `# ${title}`,
    channelName ? `**Channel:** ${channelName}` : '',
    `**Source:** ${url}`,
    `**Difficulty:** ${analysis?.difficulty || 'N/A'} · **Sentiment:** ${analysis?.sentiment || 'N/A'}`,
    `**Tags:** ${(analysis?.tags || []).join(', ')}`,
    '',
    '---',
    '',
    '## Summary',
    '',
    analysis?.summary || 'No summary available.',
    '',
    '## Key Takeaways',
    '',
    ...(analysis?.bulletPoints || []).map((b, i) => `${i + 1}. ${b}`),
    '',
    '## Key Concepts',
    '',
    ...(analysis?.keyConcepts || []).map(c => `**${c.term}** *(${c.importance})*\n${c.definition}\n`),
    '## MCQ Quiz',
    '',
    ...(analysis?.mcqs || []).map((q, i) =>
      `**Q${i + 1}.** ${q.question}\n` +
      (q.options || []).map((o, oi) => `  ${oi === q.correctAnswer ? '✅' : '○'} ${String.fromCharCode(65 + oi)}. ${o}`).join('\n') +
      (q.explanation ? `\n  > 💡 ${q.explanation}` : '') + '\n'
    ),
    '',
    '---',
    `*Generated by VidBrain AI · ${new Date().toLocaleDateString()}*`,
  ];
  return lines.filter(l => l !== null).join('\n');
};

const exportAsJSON = (video) => {
  return JSON.stringify({
    title: video.title,
    channel: video.channelName,
    url: video.url,
    analyzedAt: video.createdAt,
    analysis: video.analysis,
  }, null, 2);
};

const downloadFile = (content, filename, type) => {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

const safeFilename = (title) =>
  title.replace(/[^a-z0-9]/gi, '_').replace(/_+/g, '_').slice(0, 40).toLowerCase();

export default function ExportMenu({ video }) {
  const [open, setOpen] = useState(false);
  const ref = useRef(null);

  useEffect(() => {
    const handler = (e) => { if (ref.current && !ref.current.contains(e.target)) setOpen(false); };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, []);

  const handleMarkdown = () => {
    downloadFile(exportAsMarkdown(video), `${safeFilename(video.title)}.md`, 'text/markdown');
    setOpen(false);
  };

  const handleJSON = () => {
    downloadFile(exportAsJSON(video), `${safeFilename(video.title)}.json`, 'application/json');
    setOpen(false);
  };

  const handleText = () => {
    const { analysis } = video;
    const content = [
      video.title,
      '='.repeat(video.title.length),
      '',
      'SUMMARY',
      '-------',
      analysis?.summary || '',
      '',
      'KEY TAKEAWAYS',
      '-------------',
      ...(analysis?.bulletPoints || []).map((b, i) => `${i + 1}. ${b}`),
      '',
      'KEY CONCEPTS',
      '------------',
      ...(analysis?.keyConcepts || []).map(c => `• ${c.term}: ${c.definition}`),
    ].join('\n');
    downloadFile(content, `${safeFilename(video.title)}.txt`, 'text/plain');
    setOpen(false);
  };

  return (
    <div ref={ref} style={{ position: 'relative' }}>
      <button
        onClick={() => setOpen(!open)}
        className="btn btn-secondary btn-sm"
        style={{ gap: 6 }}
      >
        <Download size={14} /> Export <ChevronDown size={13} style={{ opacity: 0.6 }} />
      </button>

      {open && (
        <div style={{
          position: 'absolute', top: 'calc(100% + 6px)', right: 0, zIndex: 50,
          background: 'var(--bg-elevated)',
          border: '1px solid var(--border-default)',
          borderRadius: 'var(--radius-md)',
          boxShadow: 'var(--shadow-lg)',
          minWidth: 180,
          overflow: 'hidden',
          animation: 'fadeIn 0.15s ease',
        }}>
          {[
            { icon: FileText, label: 'Markdown (.md)', onClick: handleMarkdown, desc: 'Rich formatted text' },
            { icon: FileText, label: 'Plain Text (.txt)', onClick: handleText, desc: 'Simple text file' },
            { icon: Code, label: 'JSON (.json)', onClick: handleJSON, desc: 'Raw structured data' },
          ].map(({ icon: Icon, label, onClick, desc }) => (
            <button key={label} onClick={onClick} style={{
              display: 'flex', alignItems: 'center', gap: 12, width: '100%',
              padding: '10px 14px', background: 'none', border: 'none', cursor: 'pointer',
              textAlign: 'left', transition: 'background var(--transition-fast)',
              borderBottom: '1px solid var(--border-subtle)',
            }}
              onMouseEnter={e => e.currentTarget.style.background = 'var(--bg-hover)'}
              onMouseLeave={e => e.currentTarget.style.background = 'none'}
            >
              <Icon size={15} color="var(--amber)" style={{ flexShrink: 0 }} />
              <div>
                <div style={{ fontSize: 13, fontWeight: 600, fontFamily: 'var(--font-display)', color: 'var(--text-primary)' }}>{label}</div>
                <div style={{ fontSize: 11, color: 'var(--text-muted)' }}>{desc}</div>
              </div>
            </button>
          ))}
        </div>
      )}
    </div>
  );
}
